### ISSUE TITLE
Typo in comment

### ISSUE THREAD

**Issue by szepeviktor** [syntatis/wp-starter-plugin#7]
https://github.com/syntatis/wp-starter-plugin/blob/bf9e6ba4ba5e4b6050b66143a3095ab4b40919ff/inc/helpers.php#L55

stylessheet -> stylesheets

---

It would be a 10/10 WordPress starter plugin without global constants!

[_What to avoid_](https://github.com/szepeviktor/starter-plugin?tab=readme-ov-file#what-to-avoid)

**Comment by tfirdaus** [comment]
@szepeviktor thanks for the inputs. I'm contantly evaluating the technical implementation of this starter plugin in this early stage. I've also been sharing this with my peers and will certainly make some of the improvements.

**Comment by tfirdaus** [comment]
@szepeviktor thanks. This has been addressed in #9
